### ISSUE TITLE
[8.0] web_ckeditor4 does not work in email templates/mako

### ISSUE THREAD

**Issue by RoelAdriaans** [OCA/web#151]
With the web_ckeditor4 enabled, editing an email template breaks the template.

The code before saving is, for example:

``` mako
       % if object.origin:
       &nbsp;&nbsp;Order reference: ${object.origin}<br />
       % endif
```

and after saving:

``` mako
% if object.origin: &nbsp;&nbsp;Order reference: ${object.origin}<br />
% endif %
```

The missing enters break the mako formatting engine, you have to edit the template by hand.. 
This is in 8.0. 
(Ninja edit, `%endif` is not removed)

**Comment by pedrobaeza** [comment]
And `% endif` is also removed?

@antespi, you have also this issue, doesn't it?

**Comment by RoelAdriaans** [comment]
@pedrobaeza %end if is not removed, it's on a new line with the next % if next to it.
I've updated my paste.. 

https://github.com/0k/web_ckeditor/issues/4 seems to be the same issue

**Comment by pedrobaeza** [comment]
I think that has to be treated on the ckeditor4 JS widget itself, not here, but @hbrunn should say about this

**Comment by hbrunn** [comment]
To fix this, we'll have to dive into ckeditor's internals, I think. http://docs.ckeditor.com/#!/api/CKEDITOR.htmlDataProcessor seems to be a good starting point. Or this looks even better: http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-protectedSource

**Comment by antespi** [comment]
@pedrobaeza yes, we have the same issue.
@hbrunn yes, protectedSource regex maybe fix this.

**Comment by rafaelbn** [comment]
@hbrunn did you detect the same issue using https://github.com/OCA/crm/tree/8.0/newsletter when creating/editing emails templates Under Sales/Configuration/Newsletter type? (as newsletter installs ckeditor)

**Comment by hbrunn** [comment]
@RoelAdriaans-B-informed @pedrobaeza @antespi @rafaelbn 

I think @lfreeke mentioned this problem once.

Should be fixed by #158

**Comment by RoelAdriaans** [comment]
#158 did not fix this issue

**Comment by rafaelbn** [comment]
As #158 didn't fix this issue, are any of you interested in fixing it? Are you using this module en production enviroments? We are still not using this module as corrupts many standards functionalities.

**Comment by rafaelbn** [comment]
Check https://github.com/OCA/web/pull/213/ @hbrunn update ckeditor version

**Comment by rafaelbn** [comment]
@sergio-incaser @carlos-incaser as you are using web_ckeditor4 module I think you are interested in this issue. We are not using web_ckeditor4 by the moment. We need time to fix this issue and test it deeper to use with customers.

**Comment by psyray** [comment]
Hi,
This bug is still present, result after saving is the same as @RoelAdriaans-B-informed reports.
![image](https://cloud.githubusercontent.com/assets/1230954/22735955/6c7853b8-edfc-11e6-970c-115c33fdd81d.png)
![image](https://cloud.githubusercontent.com/assets/1230954/22736138/0e937952-edfd-11e6-9ef3-27f7c891e7e9.png)

Is this planned to be resolved ?

**Comment by pedrobaeza** [comment]
If the PR already merged doesn't resolve it, I don't think so, as most of us have moved on to 9.0 or uninstall the module, but I can't speak for all.

**Comment by psyray** [comment]
Thanks for quick reply ;)
Is there a way to disable ck_editor for email templating ? Or must i use this module for all html content ?

**Comment by pedrobaeza** [comment]
Not now AFAIK, as this one replaces default HTML editor.

**Comment by psyray** [comment]
Ok thanks, I will disable this module.
